# Generated by Django 5.2.1 on 2025-05-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='has_airport',
            field=models.BooleanField(default=False, verbose_name='Есть аэропорт'),
        ),
        migrations.AddField(
            model_name='city',
            name='has_train_station',
            field=models.BooleanField(default=False, verbose_name='Есть ж/д вокзал'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
    ]
