# Generated by Django 5.2.1 on 2025-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.BigIntegerField()),
                ('draftbooking_id', models.BigIntegerField(blank=True, null=True)),
                ('item_id', models.BigIntegerField()),
                ('recommendation_id', models.BigIntegerField()),
            ],
        ),
    ]
