# Generated by Django 5.2.1 on 2025-05-26 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('hotel', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='flight_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.flightticket'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='train_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.trainticket'),
        ),
        migrations.AddField(
            model_name='bookingticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingticket',
            name='flight_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.flightticket'),
        ),
        migrations.AddField(
            model_name='draftbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.draftbooking'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_bookings', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='booking.booking'),
        ),
    ]
