# Generated by Django 5.2.1 on 2025-05-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingTypeMapping',
        ),
        migrations.DeleteModel(
            name='DraftBooking',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
