# Generated by Django 5.2.1 on 2025-05-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingitem_excursion'),
        ('transport', '0008_remove_trainticket_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='hotel_room',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='train_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.trainticket'),
        ),
    ]
