# Generated by Django 5.2.1 on 2025-05-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_bookingitem_hotel_room_and_more'),
        ('hotel', '0006_roomclasstemplate_roominventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
