# Generated by Django 5.2.1 on 2025-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='excursion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='excursions/', verbose_name='Изображение'),
        ),
    ]
