# Generated by Django 5.2.1 on 2025-05-20 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0002_remove_excursion_image_url_excursion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
