# Generated by Django 5.2.1 on 2025-05-20 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0003_excursion_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='start_time',
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
