# Generated by Django 5.2.1 on 2025-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_remove_excursion_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excursionavailability',
            unique_together={('excursion', 'available_date', 'start_time')},
        ),
    ]
