# Generated by Django 5.2.1 on 2025-05-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('for_kids', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard_rooms', models.PositiveIntegerField(default=0)),
                ('superior_rooms', models.PositiveIntegerField(default=0)),
                ('deluxe_rooms', models.PositiveIntegerField(default=0)),
                ('suite_rooms', models.PositiveIntegerField(default=0)),
                ('presidential_rooms', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_class', models.CharField(choices=[('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=100)),
                ('description', models.TextField(help_text='Перечислите удобства через запятую или перенос строки', verbose_name='Описание')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Цена за ночь, ₽')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomClassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_class', models.CharField(choices=[('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='room_templates/')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Цена за ночь (₽)')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_templates', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'room_class')},
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
