# Generated by Django 5.2.1 on 2025-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_for_kids_hotel_price_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default=101, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('premium', 'Премиум'), ('luxury', 'Люкс'), ('presidential', 'Президентский')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.PositiveIntegerField(),
        ),
    ]
