# Generated by Django 5.2.1 on 2025-05-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_room_capacity_remove_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(help_text='Перечислите удобства через запятую или перенос строки', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='Цена за ночь, ₽'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(max_length=100, verbose_name='Класс номера'),
        ),
    ]
