# Generated by Django 5.2.1 on 2025-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_room_available_remove_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='deluxe_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='presidential_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='standard_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='suite_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='superior_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=100),
        ),
    ]
