# Generated by Django 5.2.1 on 2025-05-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_deluxe_rooms_hotel_presidential_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_class', models.CharField(choices=[('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='room_templates/')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Цена за ночь (₽)')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_templates', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'room_class')},
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
