# Generated by Django 5.2.1 on 2025-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('airline', models.CharField(max_length=64, verbose_name='Авиакомпания')),
                ('departure_airport', models.CharField(max_length=128, verbose_name='Откуда')),
                ('arrival_airport', models.CharField(max_length=128, verbose_name='Куда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('seats_economy', models.PositiveIntegerField(default=0, verbose_name='Мест в эконом-классе')),
                ('seats_standard', models.PositiveIntegerField(default=0, verbose_name='Мест в стандарт-классе')),
                ('seats_business', models.PositiveIntegerField(default=0, verbose_name='Мест в бизнес-классе')),
                ('seats_first', models.PositiveIntegerField(default=0, verbose_name='Мест в первом классе')),
            ],
        ),
    ]
