# Generated by Django 5.2.1 on 2025-05-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightticket',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='passenger_passport',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flightticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='transport.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightticket',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('standard', 'Стандарт'), ('business', 'Бизнес'), ('first', 'Первый')], default=1, max_length=10, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightticket',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightticket',
            name='seat_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='flightticket',
            table=None,
        ),
    ]
