# Generated by Django 5.2.1 on 2025-05-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('transport', '0003_remove_flightticket_arrival_airport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='location.city', verbose_name='Куда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='location.city', verbose_name='Откуда'),
            preserve_default=False,
        ),
    ]
