# Generated by Django 5.2.1 on 2025-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Временно забронирован до'),
        ),
    ]
