# Generated by Django 5.2.1 on 2025-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_flightticket_reserved_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'Выполняется'), ('completed', 'Выполнен')], default='scheduled', max_length=20),
        ),
    ]
