# Generated by Django 5.2.1 on 2025-05-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_city_country'),
        ('transport', '0006_flight_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, verbose_name='Номер поезда')),
                ('operator', models.CharField(max_length=64, verbose_name='Железнодорожная компания')),
                ('departure_date', models.DateTimeField(verbose_name='Дата и время отправления')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата и время прибытия')),
                ('seats_platzkart', models.PositiveIntegerField(default=0, verbose_name='Мест в плацкарте')),
                ('seats_kupe', models.PositiveIntegerField(default=0, verbose_name='Мест в купе')),
                ('seats_sv', models.PositiveIntegerField(default=0, verbose_name='Мест в СВ')),
                ('seats_business', models.PositiveIntegerField(default=0, verbose_name='Мест в бизнес-классе')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В пути'), ('completed', 'Выполнен')], default='scheduled', max_length=20)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_trains', to='location.city', verbose_name='Куда')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_trains', to='location.city', verbose_name='Откуда')),
            ],
        ),
    ]
