# Generated by Django 5.2.1 on 2025-05-20 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingitem_excursion'),
        ('transport', '0007_train'),
        ('user_profile', '0004_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainticket',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='arrival_station',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='departure_station',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='passenger_passport',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='train_number',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='train',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Временно забронирован до'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='seat_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='transport.train'),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='train_class',
            field=models.CharField(choices=[('platzkart', 'Плацкарт'), ('kupe', 'Купе'), ('sv', 'СВ'), ('business', 'Бизнес')], default='platzkart', max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер поезда'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='trainticket',
            table=None,
        ),
        migrations.CreateModel(
            name='TrainedBookingTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('train_number', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_station', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_station', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('passenger_passport', models.ForeignKey(blank=True, db_column='passenger_passport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.passport')),
            ],
            options={
                'db_table': 'booking_train_ticket',
            },
        ),
    ]
